#ifndef WARIBASHI_DRONE_H
#define WARIBASHI_DRONE_H

#define SAMPLING_INTERVAL 100

#define MOTOR_PIN_00 13
#define MOTOR_PIN_01 2
#define MOTOR_PIN_02 19
#define MOTOR_PIN_03 33

#define RECIEVE_DATA_SIZE 5

#endif